apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-autoscalar-deployement
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: camunda-autoscalar
        image: camunda-autoscalar